INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR})

find_package(Eigen3)
INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIR})

FIND_PACKAGE(Boost COMPONENTS timer REQUIRED)
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})

IF(${PROJECT_NAME}_ExpChemistry)
  FIND_PACKAGE(Cantera REQUIRED)
  INCLUDE_DIRECTORIES(${CANTERA_INCLUDE_DIR})
  SET(KIT_LIBS ${KIT_LIBS} "${CANTERA_LIBRARIES}")
ENDIF (${PROJECT_NAME}_ExpChemistry)